### ISSUE TITLE
5.1.2 Power Consumption

### ISSUE THREAD

**Issue by cujomalainey** [ECE493W18T04/android-app#23]
The WNH will need to ensure that the power limitation will not hinder the ability of the HUD to clearly display navigational information for the user in daylight. Power consumption will increase during daylight.

**Comment by cujomalainey** [comment]
@rmaarouf can I get a commit and date for when this was finished in the app?

**Comment by rmaarouf** [comment]
March 23 400ebcf1631b11976aa98d7fbc69ad3ff11f0752
